server:
  port: 8081
spring:
  data:
    mongodb:
      database: finalchallenge
      host: mongo
      port: 27017
info:
  app:
    name: City REST API
    description: City microservice for the spring boot interview challenge
    version: 1
