swagger: '2.0'
info:
  description: This is a microservice documentation for the Fast Track's final challenge.
  version: v1
  title: City REST API
  termsOfService: Terms of service
  contact:
    name: Gustavo Teixeira
    url: 'https://www.compasso.com.br'
    email: gustavoteixeira@compasso.com.br
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: 'localhost:8082'
basePath: /
tags:
  - name: city-controller
    description: City Controller to control requests to /cities

paths:

  /cities:

    post:
      tags:
        - city-controller
      summary: Method to post a new city
      operationId: postNewCityUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: cityRequestDto
          description: The city data to be saved.
          required: true
          schema:
            $ref: '#/definitions/CityRequestDto'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/CityResponseDto'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      deprecated: false
  
  '/cities/name/{name}':
    
    get:
      tags:
        - city-controller
      summary: Method to get cities by name
      operationId: getCityByNameUsingGET
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          description: Name of the city
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CityResponseDto'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      deprecated: false
  
  '/cities/state/{state}':
  
    get:
      tags:
        - city-controller
      summary: Method to get cities by state
      operationId: getCityByStateUsingGET
      produces:
        - application/json
      parameters:
        - name: state
          in: path
          description: State of the city
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CityResponseDto'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      deprecated: false

definitions:

  CityRequestDto:
    type: object
    properties:
      name:
        type: string
        example: Curitiba
        description: Name of the city.
      state:
        type: string
        example: PR
        description: State of the city.
    title: City Request Data Transfer Object

  CityResponseDto:
    type: object
    properties:
      id:
        type: string
        example: 5e7be93e634142668750b85f
        description: Unique identifier of the city.
      name:
        type: string
        example: Curitiba
        description: Name of the city.
      state:
        type: string
        example: PR
        description: State of the city.
    title: City Response Data Transfer Object
